---
title: "Data Cleaning and Preparation"
format: html
editor: visual
---

```{r}
install.packages(c("tidyverse", "here", "withr"))
```

```{r}
library(tidyverse)  
library(here)       
library(withr)      
```

```{r}
ufo_sightings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-06-20/ufo_sightings.csv')
places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-06-20/places.csv')
day_parts_map <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-06-20/day_parts_map.csv')

```

```{r}
head(ufo_sightings)
head(places)
head(day_parts_map)
```

```{r}
dir.create(here("data", "2023", "2023-06-20"), recursive = TRUE, showWarnings = FALSE)

write_csv(ufo_sightings, here("data", "2023", "2023-06-20", "ufo_sightings.csv"))
write_csv(places, here("data", "2023", "2023-06-20", "places.csv"))
write_csv(day_parts_map, here("data", "2023", "2023-06-20", "day_parts_map.csv"))
```

```{r}
glimpse(ufo_sightings)
glimpse(places)
glimpse(day_parts_map)
```

```{r}
colSums(is.na(ufo_sightings))
```

```{r}
colSums(is.na(places))
```

```{r}
colSums(is.na(day_parts_map))
```

```{r}
dim(ufo_sightings)
summary(ufo_sightings)
```

```{r}
dim(places)
summary(places)
```

```{r}
dim(day_parts_map)
summary(day_parts_map)
```

```{r}
sum(duplicated(ufo_sightings))
```
